[package]
name = "actix-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
futures = "0.3"
uuid = { version = "1.8.0", features = ["v4", "fast-rng", "macro-diagnostics"]}
derive_more = "0.99.18"
